CE103 Algorithms and Programming I HW3: C:/Users/alper/Desktop/CE103-HW3-Template-main2/CE103-HW3-Template-main/LocalizationExample/LocalizationExample/translate.h File Reference
translate.h File Reference
#include <stdbool.h>
Macros
#define ENGLISH_L "en"
#define TURKISH_L "tr"
#define EN_LANG_FILE "en.dat"
#define TR_LANG_FILE "tr.dat"
#define LANG_CONF_FILE "lang.conf"
#define APP_LANG_EN 0
#define APP_LANG_TR 1
Functions
void setTranslateLang (char *str, bool save)
void getTranslateLang (char *lang)
void printTranslateLang (int id)
Variables
int app_language
Macro Definition Documentation
APP_LANG_EN
#define APP_LANG_EN 0
APP_LANG_TR
#define APP_LANG_TR 1
EN_LANG_FILE
#define EN_LANG_FILE "en.dat"
ENGLISH_L
#define ENGLISH_L "en"
LANG_CONF_FILE
#define LANG_CONF_FILE "lang.conf"
TR_LANG_FILE
#define TR_LANG_FILE "tr.dat"
TURKISH_L
#define TURKISH_L "tr"
Function Documentation
getTranslateLang()
void getTranslateLang (char * lang)
References ENGLISH_L, fixFile(), and LANG_CONF_FILE.
Referenced by main().
printTranslateLang()
void printTranslateLang (int id)
References APP_LANG_EN, APP_LANG_TR, app_language, EN_LANG_FILE, exit(), getId(), getIdString(), and TR_LANG_FILE.
Referenced by add(), bill(), c_code(), change_language(), d_all(), d_code(), d_mainmenu(), d_quan(), d_rate(), d_search(), dbill(), del(), dis_con(), edit(), highlight(), main(), and window().
setTranslateLang()
void setTranslateLang (char * str, bool save)
References APP_LANG_EN, APP_LANG_TR, app_language, ENGLISH_L, LANG_CONF_FILE, and TURKISH_L.
Referenced by change_language(), and main().
Variable Documentation
app_language
int app_language extern
Referenced by printTranslateLang(), and setTranslateLang().