#pragma once

//messages are numbered with unique ID and this message translated text are  stored on en.dat and tr.dat files
#define MAIN_MENU 1
#define SEARCH_MENU 2
#define search1 3
#define search2 4
#define search3 5
#define search4 6
#define By_Code__ 7
#define By_Rate__ 8
#define By_Quantity__ 9
#define Back_to_main_menu__ 10
#define Calculate_Bill 11
#define Add_Goods 12
#define Edit_Goods 13
#define Display_All 14
#define Search 15
#define Delete_Goods 16
#define Change_Language 17
#define Exit 18
#define Calculate_Bill__ 19
#define Add_Goods__ 20
#define Edit_Goods__ 21
#define Display_All__ 22
#define Search__ 23
#define Delete_Goods__ 24
#define Change_Language__ 25
#define Exit__ 26
#define finish_input 27
#define enter_item_code 28
#define enter_quantity 29
#define TOTAL_AMOUNT 30
#define FASHION_WEAR 31
#define Departmental_Store 32
#define CUSTOMER_BILL 33
#define Item_Name 34
#define Enter_new_record 35
#define Enter_rate_of_the_item 36
#define Enter_quantity_of_the_item 37
#define Enter_name_of_the_item 38
#define Enter_new_record 39
#define ADD_ARTICLES 40
#define Enter_new_code_of_the_article 41
#define code_already_exists 42
#define enter_again 43
#define EDIT_RECORDS 44
#define enter_item_code 45
#define name_ 46
#define code_ 47
#define rate_ 48
#define __quantity 49
#define Do_you_want_to_edit_this_record 50
#define edit_name 51
#define edit_code 52
#define edit_rate 53
#define edit_quantity 54
#define enter_your_choice 55
#define enter_new_name 56
#define enter_new_rate 57
#define enter_new_quantity 58
#define item_edited 59
#define Item_does_not 60
#define TRY_AGAIN 61
#define Press_any_key_to_see_more 62
#define no_articles_found 63
#define Enter_lower_range 64
#define Enter_upper_range 65
#define No_items_found 66
#define RECORDS 67
#define DELETE_ARTICLES 68
#define item_deleted 69
#define enter_your_choice_then_press 70
#define enter_your_choice2 71

